[package]
name = "revault_tx"
version = "0.0.1"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"


[dependencies]
bitcoin = "0.24"
bitcoinconsensus = "0.19.0-1"
miniscript = { git = "https://github.com/darosior/rust-miniscript", branch = "avoid_recursion", features = ["compiler"] }

[dev-dependencies]
bitcoin = { version = "0.24", features = ["rand"] }
